### ISSUE TITLE
Hosting on a domain!

### ISSUE THREAD

**Issue by suryamishra59** [Arduino-Projects/Controlling-LED-using-ESP8266-UI#1]
Thank you for the project. I do have one question though! Can I host this web app on my website? Would it work? I tried hosting it up on my website i.e madebysurya.com/WifiLed.

Now how do I connect it with ESP8266? Please help!

Thanks again

**Comment by last-stand** [comment]
Sorry for your inconvenience. Please read this blog [Control LED from web app using ESP8266 Serial WIFI Wireless Transceiver Module and Arduino](https://jaiprakblogs.wordpress.com/2016/05/24/control-led-from-web-app-using-esp8266-serial-wifi-wireless-transceiver-module-and-arduino/)  for more information. I have mentioned everything here steps by step. If you don't want to use Arduino board with ESP wifi module you can try this out [ESPWifiServer](https://github.com/Arduino-and-RaspberryPi/ESPWifiServer) . The only thing is, you have to remove the HTML part from given program in this link and you will have to use this WEB-App instead.
